name: presta

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
#  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - php-version: '7.1'
            branch: '1.7.4.0'
            composerv1: 1
            phpunit-version: 'phpunit:6.4.3'
          - php-version: '7.2'
            branch: '1.7.4.0'
            composerv1: 1
            phpunit-version: 'phpunit:6.4.3'

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: prestashop
          MYSQL_USER: test
          MYSQL_PASSWORD: prestashop_demo
          #MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - uses: actions/checkout@v2
      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: xdebug
          tools: composer:v2, ${{ matrix.phpunit-version }}
          extensions: gd, mbstring, zip, mcrypt, pdo_mysql, dom
      - name: Start mysql service
        run: sudo /etc/init.d/mysql start
      - name: Status mysql service
        run: sudo systemctl status mysql
      - name: Test MySQL
        run: mysql -u root -proot -e "show databases;"
      - name: Install PrestaShop
        env:
          BRANCH: ${{ matrix.branch }}
          COMPOSERV1: ${{ matrix.composerv1 }}
        run: make before_script
      - name: Run tests
        env:
          BRANCH: ${{ matrix.branch }}
          COMPOSERV1: ${{ matrix.composerv1 }}
        run: make test
